Implement index view
kjcioffi/django-movies pull request #14
Opened 2024-06-10 20:26 UTC by kjcioffi

- Refactored requirements into a folder for improved dependency management.
- Implemented business logic to route movies playing in theaters to a view.
- Implemented a view that populates movies playing in theaters using previously mentioned business logic written in movie_api_utils.py

2024-06-10 22:48 UTC, ryaustin requested changes
Great submission here Kevin. Your imports are clean and the code just works.
Most of my commentary is around the unhappy times when things that you expect to work don't (such as the API being down).

I recommend making some specific changes that I will breakout as issues.

2024-06-10 22:48 UTC, ryaustin commented on movies/tests/views/test_movie_list_view.py
> +        self.assertTrue(self.movies_in_context)
To make this test more robust, it might be worthwhile to ensure there are no errors. 
When I ran this test it passed successfully - which I expected to fail since I don't have the API key set yet.
Here is the resolve of self.movies_in_context: `{'status_code': 7, 'status_message': 'Invalid API key: You must be granted a valid key.', 'success': False}`

So how can you 1: make the test more robust? 
Does it make sense to test a scenario where there is no API key (success: False)?

2024-06-10 22:48 UTC, ryaustin commented on core/settings.py
> +if DEBUG_TOOLBAR_ENABLED:
This is well implemented. 
To make it even more robust I suggest placing "debug_toolbar" and the debug_toolbar middleware string in a constant and using it to increase readability & maintainability `DEBUG_TOOLBAR = "debug_toolbar"`

2024-06-10 22:48 UTC, ryaustin commented on core/settings.py
> +        ]
here we aren't checking if the debug_toolbar.middleware is in the middleware before removing it.
I guess it can be pretty safely assumed that it is.

2024-06-10 22:48 UTC, ryaustin commented on core/settings.py
> +ALLOWED_HOSTS = ["*"]
I recommend managing allowed_hosts explicitly from day 1. This reduces headache and troubleshooting when it's time to lockdown and deploy. Right now it's localhost and 127.x.x. later you might use an environment variable to set ALLOWED_HOSTS appropriately.
 `ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost"])`

2024-06-10 22:48 UTC, ryaustin commented on core/urls.py
> +    path("", include("movies.urls", namespace="movies")),
`namespaces are a honking great idea`

2024-06-10 22:48 UTC, ryaustin commented on movies/movie_api_utils.py
Looking great here. Consider exception handling when using requests to manage potential issues like network errors or invalid responses. Also, exception handling is considered foundational knowledge for the pcpd-p cert.

2024-06-10 22:48 UTC, ryaustin commented on movies/views.py
here we can make several small improvements for robustness, readability and maintainability of your code:
- error handling when calling requests - you might consider making this call to requests a part of your MovieApiUtils class so that you are not constantly dealing with exception handling in your views.
- Type hints, It’s generally recommended to use Dict from typing for clarity and consistency, especially when sharing code with others. small 'd' still works but it's one of those things that might cause a head-scratcher if someone else with a older version of python runs your code.
- You want to check if your response is valid before requesting JSON. here you can use response.raise_for_status() because It helps ensure that your code gracefully handles situations where an HTTP request fails.

2024-06-13 11:33 UTC, ryaustin commented
Hi Kevin, please push the latest changes made on 12-Jun-24 along with the working tests so that we can merge this PR.

2024-06-13 19:36 UTC, kjcioffi commented
Ready for a final (hopefully) review

cc @ryaustin

2024-06-14 06:17 UTC, ryaustin approved these changes
HI Kevin, great job with the changes.
My tests failed but I can tell that it has to do with the API key not being authenticated. This is something we can look at together but does not prevent this code from being merged in as that can be reviewed as a separate issue. Great job.

2024-06-14 06:17 UTC, ryaustin commented
Go ahead and merge whenever you're ready.

2024-06-14 12:20 UTC, merged