Fixed issue with formatting the date in the movie list view HTML template.
kjcioffi/django-movies pull request #25
Opened 2024-06-18 16:45 UTC by kjcioffi

- Implemented a method in movie api utils to handle converting date strings to datetime objects.
- Incorporated the method into the MovieListView.
- Added test coverage to support the feature.

2024-06-18 19:27 UTC, ryaustin requested changes
Would like to get a better understanding on the filter mechanism.

2024-06-18 19:27 UTC, ryaustin commented on movies/movie_api_utils.py
> +    def convert_date_string_into_object(self, movies, *, filter: str = None):
The docstring here could benefit from an example of how the filter would be used.
Is it to search for a certain movie? date?

2024-06-18 19:27 UTC, ryaustin commented on movies/movie_api_utils.py
> +            movies_to_process = movies if filter is None else movies[filter]
here is also a potential issue (if searching for a string pattern). You get a single result vs every result that matches your filter.

2024-06-18 19:27 UTC, ryaustin commented on movies/tests/test_movie_api_utils.py
> +            self.movie_api_utils.convert_date_string_into_object(movies, filter=filter)
Include a test for a good filter.
- happy-path tests prove that what you intended works and allows for other developers to quickly understand the code by simply reviewing the tests.

2024-06-18 19:41 UTC, ryaustin commented
- [ ] take a look at the dateparser library apart of stdlib: https://dateparser.readthedocs.io/en/latest/

Dateparser handles errors and exceptions better than the datetime library and returns a datetime object. You cannot trust external data and one malformed date or null value can cause exceptions on your main page - this won't happen with dateparser.

You can consider using it in several ways. 
1. As a fill-in for .strftime as used in your code, 
2. As a custom template filter that you pass string dates (from the template).

2024-06-18 20:08 UTC, kjcioffi commented
I was not aware date parser existed. I am most certainly interested in using it, however, I don't follow what you mean by using it as a custom template filter. 

Are we talking about something that can be used with an HTML template or is this still about the **filter** keyword argument?

2024-06-18 20:51 UTC, ryaustin commented
Awesome. date parser is a game changer when you discover it. You can almost through any kind of date at it and it will either convert it or fail gracefully.

Its outside of the scope of the project since you already created the method to convert strings (I believe this approach is best), but the custom filter would work in the same way the built-in date filter works as in: ` movie.release_date | date:"..."` 

It allows you to extend the template with functions that you can pass arguments to. So if you were to create a custom filter called string_to_date, your code becomes `movie.release_date | string_to_date:movie.release_date` or something like that. Checkout this link to learn more about this powerful pattern: https://docs.djangoproject.com/en/5.0/howto/custom-template-tags/

2024-06-19 13:42 UTC, ryaustin approved these changes
- filter has been more clearly defined
- happy path test gives an example of what is expected
- No regression expected
- Looks good to merge

2024-06-19 13:42 UTC, ryaustin commented on movies/movie_api_utils.py
> +            movies_to_process = movies if filter is None else movies[filter]
Okay, looks like this is resolved.

2024-06-19 15:36 UTC, merged